### ISSUE TITLE
مشکل در اضافه کردن دامنه جدید به لیست

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/iran-iplist#1]
سلام مهندس عزیز لست دامنه ها و آی پی های موجود نسبت به لیست اصلی بسیار کمه و وقتی بیشتر از یه تعداد اضافه میکنم دستی قبول نمیکنه آیا راهی هست از geositeوip استفاده کرد یا کل لیست تقریبا صدو بیست هزار دامنه و ip رو جا داد داخل لیست

**Comment by amirhosseinchoghaei** [comment]
درود ، اصلا نیازی نیستش شما دامنه اضافه کنید ، من همراه دامنه 99 درصد از آی پی لیست های ایران رو هم اد کردم که تکمیل کننده ترافیک ایران هستش ... پشت هر دامنه یک آی پی هستش که من تمام آی پی هارو اد کردم پس دامنه مهم نیست حتی اگر تمام دامنه هارو هم پاک کنید باز آی پی لیست ها کارشون رو انجام میدن ...
توی اون بخش فقط آی پی و دامین ساپورت میشه نه geosite و چیزای دیگه ...
